### PR TITLE
added cryptic-network to docker-compose

### PR DESCRIPTION
**Pull request by felixevers**
## Description

- added crytpic-network (microservice)
- changed to mysql in `docker-compose.debug.yml`

## Motivation and Context
Docker-Compose is supporting an easy start for beginners and developers.

## How Has This Been Tested?
Tested with docker-compose.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by Defelo — CHANGES_REQUESTED** [review]
use sqlite for the `docker-compose.debug.yml` instead of mysql

**Review by tanneberger — CHANGES_REQUESTED** [review]
Add Inventory, New Python3-Lib needs Volume for Logging Files

**Comment by felixevers** [comment]
@Defelo We have to use mysql, because sqlite3 is not working with multithreading.
@SpartanerSpaten I will add the volume for that logging files, but the inventory microservice is not included in this issue (task).

**Comment by tanneberger** [comment]
Just add Inventory too your task ;)  @use-to

**Comment by felixevers** [comment]
> Just add Inventory too your task ;) @use-to

Just create an issue @SpartanerSpaten

**Comment by tanneberger** [comment]
are you serious ... and you wonder why development takes ages. @use-to 
Its copy paste with changing some names ... and dont forget adding logging volumes

**Review by tanneberger — CHANGES_REQUESTED** [review]
Maybe add new Python3-Lib specific stuff in the production docker-compose and leave it open so a sys admin can fill it out.
```
DSN:
RELEASE:
PATH_LOGFILE:
```
For path log_file pls make sure you also created a volume or the path exists inside the container

But gj

**Review by Defelo — APPROVED** [review]

**Pull request merged**
